package rules;

import org.precondition.model.wrapper.UcenterPreconditionObjectWrapper
import org.precondition.limit.Limiter
import java.sql.Wrapper
import org.precondition.model.Result
import java.util.concurrent.TimeUnit

global Limiter limter

rule "ucenter_same_ip_ten_minute"
    salience 9998
    when $wrapper:UcenterPreconditionObjectWrapper(limter.currentValue(ip+"_ten_minute_"+type) >= limter.currentValue("ten_minute_"+type))
    then  $wrapper.setResult(new Result(1));
end

rule "ucenter_same_ip_ten_minute_update"
    salience 9999
    when $wrapper:UcenterPreconditionObjectWrapper( postProcess==true)
    then limter.incrementCurrentValue($wrapper.getIp()+"_ten_minute_"+$wrapper.getType(),TimeUnit.MINUTES.toSeconds(10));
end
