package rules;

import org.precondition.model.wrapper.UcenterPreconditionObjectWrapper
import org.precondition.limit.Limiter
import java.sql.Wrapper
import org.precondition.model.Result
import java.util.concurrent.TimeUnit
import org.slf4j.Logger


global Limiter limter
global Logger logger
function String getIPV4SegmentForC(String ip){
    String[] ipSegment = ip.split("\\.");
    return ipSegment[0]+"."+ipSegment[1]+"."+ipSegment[2]+".*";
}

rule "ucenter_c_ip_hour"
    salience 9968
    activation-group "ucenter_c_ip_hour"
    when $wrapper:UcenterPreconditionObjectWrapper(validateResult.level<1 , limter.currentValue(getIPV4SegmentForC(ip)+"_c_ip_hour_"+type.toString()) >= limter.currentLimit("c_ip_hour_"+type.toString()))
    then  $wrapper.setValidateResult(new Result(1));
                logger.info("valid fail ucenter_c_ip_hour , c_ip={} result={} ",getIPV4SegmentForC($wrapper.getIp()) , $wrapper);
                update($wrapper);
end

rule "ucenter_c_ip_hour_update"
    salience 9969
    activation-group "ucenter_c_ip_hour"
    when $wrapper:UcenterPreconditionObjectWrapper( postProcess==true)
    then limter.incrementCurrentValue(getIPV4SegmentForC($wrapper.getIp())+"_c_ip_hour_"+$wrapper.getType(),TimeUnit.HOURS.toSeconds(1));
end
